version: '3.9'

services:
  
  spring-boot-app-non-virtual:
    image: amazoncorretto:21
    volumes:
      - ./spring-boot-demo/build/libs/spring-boot-demo-1.0.jar:/app.jar
    ports:
      - "8081:8080"
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: non-virtual
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
    command: java -jar /app.jar com.example.demo.DemoApplication

  spring-boot-app-virtual:
    image: amazoncorretto:21
    volumes:
      - ./spring-boot-demo/build/libs/spring-boot-demo-1.0.jar:/app.jar
    ports:
      - "8082:8080"
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: virtual
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
    command: java -jar /app.jar com.example.demo.DemoApplication

  spring-boot-app-mono-virtual:
    image: amazoncorretto:21
    volumes:
      - ./spring-boot-demo/build/libs/spring-boot-demo-1.0.jar:/app.jar
    ports:
      - "8083:8080"
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: mono-virtual
      SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
    command: java -jar /app.jar com.example.demo.DemoApplication

  nodejs-app:
    image: navikt/node-express
    volumes:
      - ./nodejs-demo/src/app.js:/app.js
    ports:
      - "8084:3000"
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
    command: node /app.js
    